//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.7.0
//     from Assets/Scripts/Farming/PlayerFarmingInputAction.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @PlayerFarmingInputAction: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @PlayerFarmingInputAction()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""PlayerFarmingInputAction"",
    ""maps"": [
        {
            ""name"": ""Farming"",
            ""id"": ""ae710741-ffde-4acc-81f0-31ef553f41de"",
            ""actions"": [
                {
                    ""name"": ""LeftClick"",
                    ""type"": ""Button"",
                    ""id"": ""646398b1-7fde-4d86-bcdb-65fe58e27f7f"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Slot01"",
                    ""type"": ""Button"",
                    ""id"": ""b0268285-3b66-4789-89fa-f00a88f5cdcf"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Slot02"",
                    ""type"": ""Button"",
                    ""id"": ""dedf43a0-fcd9-4624-8dd3-1b66d2a0fa87"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Slot03"",
                    ""type"": ""Button"",
                    ""id"": ""79ad27a9-4da7-4f55-bee1-9c3aed6fceb0"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Slot04"",
                    ""type"": ""Button"",
                    ""id"": ""ac5bf7b6-c640-47c5-b256-ead5141155e8"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Slot05"",
                    ""type"": ""Button"",
                    ""id"": ""525c321b-d638-4fa5-bf7f-19f7951eb449"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Slot06"",
                    ""type"": ""Button"",
                    ""id"": ""1034767f-4841-4d2a-922e-57a1e4ca86d7"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Slot07"",
                    ""type"": ""Button"",
                    ""id"": ""c883c651-ac10-4067-8621-e44f5d2f1e1f"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Slot08"",
                    ""type"": ""Button"",
                    ""id"": ""0cd8bca7-5b3d-4500-a5c6-8a7e13cef1a6"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Slot09"",
                    ""type"": ""Button"",
                    ""id"": ""02757f6e-40be-4a5f-8aa5-5793984fad96"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Tab"",
                    ""type"": ""Button"",
                    ""id"": ""2fd93813-6afa-4f4f-b1ea-c25af4d0dda5"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""LeftShift"",
                    ""type"": ""Button"",
                    ""id"": ""e27fe967-97d7-4fb3-a4ed-d8085e21a028"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Spacebar"",
                    ""type"": ""Button"",
                    ""id"": ""99c5c383-4962-4168-9ca1-c8f5125a5c35"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""972a7e63-919a-4d6b-9e48-51ad7fd45e02"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LeftClick"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""297eb8de-0344-476c-ae13-886f7c89493c"",
                    ""path"": ""<Keyboard>/1"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Slot01"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""9bc8276c-7e26-4445-b25f-f59b54cb336b"",
                    ""path"": ""<Keyboard>/2"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Slot02"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""84e25250-1c1d-412d-82a9-51db28d9940c"",
                    ""path"": ""<Keyboard>/3"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Slot03"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""175f7511-d2d1-4ce6-baff-7994359cf782"",
                    ""path"": ""<Keyboard>/4"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Slot04"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b88a86fb-9c16-4621-baf1-d39ce0cf8402"",
                    ""path"": ""<Keyboard>/5"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Slot05"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""31ad1cd2-d20a-45f7-8403-5b37d567f988"",
                    ""path"": ""<Keyboard>/6"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Slot06"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""be2215ce-01f5-4b9f-91ad-237e2ae3e048"",
                    ""path"": ""<Keyboard>/7"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Slot07"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f91c6f1c-434b-4f6c-bc25-695f8b6d36ce"",
                    ""path"": ""<Keyboard>/8"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Slot08"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""9e59d0f6-4084-4f32-9543-db5dd4da0454"",
                    ""path"": ""<Keyboard>/tab"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Tab"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""3c077020-e681-4cf0-a03e-d6c5301426a5"",
                    ""path"": ""<Keyboard>/9"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Slot09"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""6f072738-d91f-4c7e-a1ac-028c6ab76cf6"",
                    ""path"": ""<Keyboard>/leftShift"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LeftShift"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""385e0fe0-26df-4349-8622-369c4933aed0"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Spacebar"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // Farming
        m_Farming = asset.FindActionMap("Farming", throwIfNotFound: true);
        m_Farming_LeftClick = m_Farming.FindAction("LeftClick", throwIfNotFound: true);
        m_Farming_Slot01 = m_Farming.FindAction("Slot01", throwIfNotFound: true);
        m_Farming_Slot02 = m_Farming.FindAction("Slot02", throwIfNotFound: true);
        m_Farming_Slot03 = m_Farming.FindAction("Slot03", throwIfNotFound: true);
        m_Farming_Slot04 = m_Farming.FindAction("Slot04", throwIfNotFound: true);
        m_Farming_Slot05 = m_Farming.FindAction("Slot05", throwIfNotFound: true);
        m_Farming_Slot06 = m_Farming.FindAction("Slot06", throwIfNotFound: true);
        m_Farming_Slot07 = m_Farming.FindAction("Slot07", throwIfNotFound: true);
        m_Farming_Slot08 = m_Farming.FindAction("Slot08", throwIfNotFound: true);
        m_Farming_Slot09 = m_Farming.FindAction("Slot09", throwIfNotFound: true);
        m_Farming_Tab = m_Farming.FindAction("Tab", throwIfNotFound: true);
        m_Farming_LeftShift = m_Farming.FindAction("LeftShift", throwIfNotFound: true);
        m_Farming_Spacebar = m_Farming.FindAction("Spacebar", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Farming
    private readonly InputActionMap m_Farming;
    private List<IFarmingActions> m_FarmingActionsCallbackInterfaces = new List<IFarmingActions>();
    private readonly InputAction m_Farming_LeftClick;
    private readonly InputAction m_Farming_Slot01;
    private readonly InputAction m_Farming_Slot02;
    private readonly InputAction m_Farming_Slot03;
    private readonly InputAction m_Farming_Slot04;
    private readonly InputAction m_Farming_Slot05;
    private readonly InputAction m_Farming_Slot06;
    private readonly InputAction m_Farming_Slot07;
    private readonly InputAction m_Farming_Slot08;
    private readonly InputAction m_Farming_Slot09;
    private readonly InputAction m_Farming_Tab;
    private readonly InputAction m_Farming_LeftShift;
    private readonly InputAction m_Farming_Spacebar;
    public struct FarmingActions
    {
        private @PlayerFarmingInputAction m_Wrapper;
        public FarmingActions(@PlayerFarmingInputAction wrapper) { m_Wrapper = wrapper; }
        public InputAction @LeftClick => m_Wrapper.m_Farming_LeftClick;
        public InputAction @Slot01 => m_Wrapper.m_Farming_Slot01;
        public InputAction @Slot02 => m_Wrapper.m_Farming_Slot02;
        public InputAction @Slot03 => m_Wrapper.m_Farming_Slot03;
        public InputAction @Slot04 => m_Wrapper.m_Farming_Slot04;
        public InputAction @Slot05 => m_Wrapper.m_Farming_Slot05;
        public InputAction @Slot06 => m_Wrapper.m_Farming_Slot06;
        public InputAction @Slot07 => m_Wrapper.m_Farming_Slot07;
        public InputAction @Slot08 => m_Wrapper.m_Farming_Slot08;
        public InputAction @Slot09 => m_Wrapper.m_Farming_Slot09;
        public InputAction @Tab => m_Wrapper.m_Farming_Tab;
        public InputAction @LeftShift => m_Wrapper.m_Farming_LeftShift;
        public InputAction @Spacebar => m_Wrapper.m_Farming_Spacebar;
        public InputActionMap Get() { return m_Wrapper.m_Farming; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(FarmingActions set) { return set.Get(); }
        public void AddCallbacks(IFarmingActions instance)
        {
            if (instance == null || m_Wrapper.m_FarmingActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_FarmingActionsCallbackInterfaces.Add(instance);
            @LeftClick.started += instance.OnLeftClick;
            @LeftClick.performed += instance.OnLeftClick;
            @LeftClick.canceled += instance.OnLeftClick;
            @Slot01.started += instance.OnSlot01;
            @Slot01.performed += instance.OnSlot01;
            @Slot01.canceled += instance.OnSlot01;
            @Slot02.started += instance.OnSlot02;
            @Slot02.performed += instance.OnSlot02;
            @Slot02.canceled += instance.OnSlot02;
            @Slot03.started += instance.OnSlot03;
            @Slot03.performed += instance.OnSlot03;
            @Slot03.canceled += instance.OnSlot03;
            @Slot04.started += instance.OnSlot04;
            @Slot04.performed += instance.OnSlot04;
            @Slot04.canceled += instance.OnSlot04;
            @Slot05.started += instance.OnSlot05;
            @Slot05.performed += instance.OnSlot05;
            @Slot05.canceled += instance.OnSlot05;
            @Slot06.started += instance.OnSlot06;
            @Slot06.performed += instance.OnSlot06;
            @Slot06.canceled += instance.OnSlot06;
            @Slot07.started += instance.OnSlot07;
            @Slot07.performed += instance.OnSlot07;
            @Slot07.canceled += instance.OnSlot07;
            @Slot08.started += instance.OnSlot08;
            @Slot08.performed += instance.OnSlot08;
            @Slot08.canceled += instance.OnSlot08;
            @Slot09.started += instance.OnSlot09;
            @Slot09.performed += instance.OnSlot09;
            @Slot09.canceled += instance.OnSlot09;
            @Tab.started += instance.OnTab;
            @Tab.performed += instance.OnTab;
            @Tab.canceled += instance.OnTab;
            @LeftShift.started += instance.OnLeftShift;
            @LeftShift.performed += instance.OnLeftShift;
            @LeftShift.canceled += instance.OnLeftShift;
            @Spacebar.started += instance.OnSpacebar;
            @Spacebar.performed += instance.OnSpacebar;
            @Spacebar.canceled += instance.OnSpacebar;
        }

        private void UnregisterCallbacks(IFarmingActions instance)
        {
            @LeftClick.started -= instance.OnLeftClick;
            @LeftClick.performed -= instance.OnLeftClick;
            @LeftClick.canceled -= instance.OnLeftClick;
            @Slot01.started -= instance.OnSlot01;
            @Slot01.performed -= instance.OnSlot01;
            @Slot01.canceled -= instance.OnSlot01;
            @Slot02.started -= instance.OnSlot02;
            @Slot02.performed -= instance.OnSlot02;
            @Slot02.canceled -= instance.OnSlot02;
            @Slot03.started -= instance.OnSlot03;
            @Slot03.performed -= instance.OnSlot03;
            @Slot03.canceled -= instance.OnSlot03;
            @Slot04.started -= instance.OnSlot04;
            @Slot04.performed -= instance.OnSlot04;
            @Slot04.canceled -= instance.OnSlot04;
            @Slot05.started -= instance.OnSlot05;
            @Slot05.performed -= instance.OnSlot05;
            @Slot05.canceled -= instance.OnSlot05;
            @Slot06.started -= instance.OnSlot06;
            @Slot06.performed -= instance.OnSlot06;
            @Slot06.canceled -= instance.OnSlot06;
            @Slot07.started -= instance.OnSlot07;
            @Slot07.performed -= instance.OnSlot07;
            @Slot07.canceled -= instance.OnSlot07;
            @Slot08.started -= instance.OnSlot08;
            @Slot08.performed -= instance.OnSlot08;
            @Slot08.canceled -= instance.OnSlot08;
            @Slot09.started -= instance.OnSlot09;
            @Slot09.performed -= instance.OnSlot09;
            @Slot09.canceled -= instance.OnSlot09;
            @Tab.started -= instance.OnTab;
            @Tab.performed -= instance.OnTab;
            @Tab.canceled -= instance.OnTab;
            @LeftShift.started -= instance.OnLeftShift;
            @LeftShift.performed -= instance.OnLeftShift;
            @LeftShift.canceled -= instance.OnLeftShift;
            @Spacebar.started -= instance.OnSpacebar;
            @Spacebar.performed -= instance.OnSpacebar;
            @Spacebar.canceled -= instance.OnSpacebar;
        }

        public void RemoveCallbacks(IFarmingActions instance)
        {
            if (m_Wrapper.m_FarmingActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IFarmingActions instance)
        {
            foreach (var item in m_Wrapper.m_FarmingActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_FarmingActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public FarmingActions @Farming => new FarmingActions(this);
    public interface IFarmingActions
    {
        void OnLeftClick(InputAction.CallbackContext context);
        void OnSlot01(InputAction.CallbackContext context);
        void OnSlot02(InputAction.CallbackContext context);
        void OnSlot03(InputAction.CallbackContext context);
        void OnSlot04(InputAction.CallbackContext context);
        void OnSlot05(InputAction.CallbackContext context);
        void OnSlot06(InputAction.CallbackContext context);
        void OnSlot07(InputAction.CallbackContext context);
        void OnSlot08(InputAction.CallbackContext context);
        void OnSlot09(InputAction.CallbackContext context);
        void OnTab(InputAction.CallbackContext context);
        void OnLeftShift(InputAction.CallbackContext context);
        void OnSpacebar(InputAction.CallbackContext context);
    }
}
